### ISSUE TITLE
Honest Proposal

### ISSUE THREAD

**Issue by Russ93** [ng-infinite-scroll/ng-infinite-scroll-bower#2]
Please change the name on `ng-infinite-scroll-npm-is-better-than-bower`. `Universal`, `Disney`, and `IBM` use `bower` for legacy reasons and we would love to incorporate this module very badly but our business, is very confused about the name.

**Comment by graingert** [comment]
It's back to ngInfiniteScroll now, but the bower build is unsupported

**Comment by graingert** [comment]
Switch to yarn, it will let you mix npm and bower packages

**Comment by graingert** [comment]
Please also do not incorporate this module into new builds. You should use virtualRepeat from Google's angular-materiel
